osx_image: xcode10.2
language: swift

before_install: 
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet 
  - gem install cocoapods --pre --no-rdoc --no-ri --no-document --quiet 
  - pod --version
  - pod setup --silent > /dev/null
  - pod repo update --silent
  - xcpretty --version
  - xcodebuild -version
  - xcodebuild -showsdks
  # - pod install --project-directory=Example 

script:
  - pod lib lint --allow-warnings --no-clean --verbose
